version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: pii-server/Dockerfile
    volumes:
      - ../pii-server:/app/pii-server
      - ../tiny-pii:/app/tiny-pii

    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://piiuser:TowardsFairAI@db:5432/piidatabase
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ../pii-frontend
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=piiuser
      - POSTGRES_PASSWORD=TowardsFairAI
      - POSTGRES_DB=piidatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
